"""
This file contains the definitions of the record fields.
The definitions are used to normalize the record data.
"""

record_definitions = {
    "last_updated": {"type": "date"},
    "date_normalized": {"type": "string"},
    "collectors": {"type": "link_list"},
    "locations": {"type": "link_list"},
    "potrait": {"type": "link"},
    "series": {"type": "link_list_hierarchy"},
    "desc_data": {"type": "key_value_dicts"},
    "availability": {"type": "label_dict"},
    "contractual_status_normalized": {"type": "string"},
    "other_legal_restrictions_normalized": {"type": "string"},
    "availability_normalized": {"type": "string"},
    "registration_id": {"type": "string"},
    "date_from": {"type": "string"},
    "content_types": {"type": "link_list_hierarchy"},
    "created_by": {"type": "string"},
    "id": {"type": "string"},
    "other_legal_restrictions": {"type": "label_dict"},
    "subjects": {"type": "link_list_hierarchy"},
    "admin_data": {"type": "key_value_dicts"},
    "type": {"type": "string"},
    "rights_notes": {"type": "string"},
    "admin_notes": {"type": "string"},
    "thumbnail": {"type": "url"},
    "resources": {"type": "key_value_dicts"},
    "schema": {"type": "string"},
    "curators": {"type": "link_list"},
    "copyright_status": {"type": "label_dict"},
    "copyright_status_normalized": {"type": "string_list"},
    "collection": {"type": "link_dict"},
    "last_updated_by": {"type": "string"},
    "original_id": {"type": "string"},
    "date_to": {"type": "string"},
    "representations": {"type": "representations"},  # special type
    "collection_tags": {"type": "link_list_hierarchy"},
    "created": {"type": "date"},
    "summary": {"type": "string"},
    "usability": {"type": "label_dict"},
    "organisations": {"type": "link_list"},
    "people": {"type": "link_list"},
    "objects": {"type": "link_list"},
    "events": {"type": "link_list"},
    "ordering_normalized": {"type": "string_list"},
    "creators": {"type": "link_list"},
    "desc_notes": {"type": "string"},
    "heading": {"type": "string"},
}
