resource_definitions = {
    # creators
    "date_from": {"type": "string"},
    "date_to": {"type": "string"},
    "description": {"type": "paragraphs"},
    # "display_label": {"type": "string"},
    "domain": {"type": "string"},
    "local_area": {"type": "string"},
    "gender": {"type": "string"},
    "firstnames": {"type": "string_list"},
    "lastnames": {"type": "string_list"},
    "occupation": {"type": "string_list"},
    "industry": {"type": "string_list"},
    "collectors_link": {"type": "link_list"},
    "creators_link": {"type": "link_list"},
    "sources_normalized": {"type": "string_list"},
    # people
    "content_and_scope": {"type": "paragraphs"},
    "date_of_birth": {"type": "string"},
    "date_of_death": {"type": "string"},
    "place_of_birth": {"type": "string"},
    "place_of_death": {"type": "string"},
    # collections
    "summary": {"type": "string"},
    "access": {"type": "paragraphs"},
    "legal_status": {"type": "paragraphs"},
    "level_of_digitisation": {"type": "paragraphs"},
    "citation": {"type": "paragraphs"},
    "custodial_history": {"type": "paragraphs"},
    "level_of_kassation": {"type": "paragraphs"},
    "accrual_status": {"type": "paragraphs"},
    "system_of_arrangement": {"type": "paragraphs"},
    "archival_history": {"type": "paragraphs"},
    "extent": {"type": "paragraphs"},
    "bulk_years": {"type": "paragraphs"},
    "accumulation_range": {"type": "paragraphs"},
    "outer_years": {"type": "string"},
    # locations
    "name": {"type": "string"},
    "addr_nr": {"type": "string"},
    "zipcode": {"type": "string"},
    "display_label": {"type": "string"},
    "latitude_longitude_normalized": {"type": "string"},
    "parish": {"type": "string"},
    "rotation": {"type": "string"},
    # "collectors": {"type": "link_list"},
    # "locations": {"type": "link_list"},
    # "potrait": {"type": "link"},
    # "series": {"type": "link_list_hierarchy"},
    # "desc_data": {"type": "key_value_dicts"},
    # "availability": {"type": "label_dict"},
    # "contractual_status_normalized": {"type": "string"},
    # "other_legal_restrictions_normalized": {"type": "string"},
    # "availability_normalized": {"type": "string"},
    # "registration_id": {"type": "string"},
    # "date_from": {"type": "string"},
    # "content_types": {"type": "link_list_hierarchy"},
    # "created_by": {"type": "string"},
    # "id": {"type": "string"},
    # "other_legal_restrictions": {"type": "label_dict"},
    # "subjects": {"type": "link_list_hierarchy"},
    # "admin_data": {"type": "key_value_dicts"},
    # "type": {"type": "string"},
    # "rights_notes": {"type": "string"},
    # "admin_notes": {"type": "string"},
    # "thumbnail": {"type": "url"},
    # "resources": {"type": "key_value_dicts"},
    # "schema": {"type": "string"},
    # "curators": {"type": "link_list"},
    # "copyright_status": {"type": "label_dict"},
    # "copyright_status_normalized": {"type": "string_list"},
    # "collection": {"type": "link_dict"},
    # "last_updated_by": {"type": "string"},
    # "original_id": {"type": "string"},
    # "date_to": {"type": "string"},
    # "representations": {"type": "representations"},  # special type
    # "collection_tags": {"type": "link_list_hierarchy"},
    # "created": {"type": "date"},
    # "summary": {"type": "string"},
    # "usability": {"type": "label_dict"},
    # "organisations": {"type": "link_list"},
    # "people": {"type": "link_list"},
    # "objects": {"type": "link_list"},
    # "events": {"type": "link_list"},
    # "ordering_normalized": {"type": "string_list"},
    # "creators": {"type": "link_list"},
    # "desc_notes": {"type": "string"},
    # "heading": {"type": "string"},
}
